# Generated by Django 3.2.13 on 2022-10-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_movie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie_url',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
