# Generated by Django 3.2.13 on 2022-10-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie_name',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie_url',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
